//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaizenTDSMvcAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityPerson
    {
        public System.Guid ID_PK { get; set; }
        public System.Guid ActivityID_FK { get; set; }
        public Nullable<System.Guid> PersonID_FK { get; set; }
        public Nullable<System.Guid> TitleLookupID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string Designation { get; set; }
        public System.Guid InvolvementTypeLookupID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.Guid> GenderLookupID { get; set; }
        public Nullable<System.Guid> MaritalStatusLookupID { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<System.Guid> HairColorLookupID { get; set; }
        public Nullable<System.Guid> EyeColorLookupID { get; set; }
        public Nullable<bool> IsEmployee { get; set; }
        public string EmployeeNumber { get; set; }
        public string FlagNotes { get; set; }
        public byte[] PersonPhoto { get; set; }
        public Nullable<bool> IsInjured { get; set; }
        public Nullable<bool> IsFirstAid { get; set; }
        public Nullable<bool> IsHospitalized { get; set; }
        public Nullable<bool> IsInterviewed { get; set; }
        public string SupplementalInformation { get; set; }
        public Nullable<short> SysGMTOffset_SI { get; set; }
        public string SysAuditCBUserID_NV { get; set; }
        public string SysAuditCBMachineID_NV { get; set; }
        public Nullable<System.DateTime> SysAuditCBDateTime_DT { get; set; }
        public string SysAuditLMUserID_NV { get; set; }
        public string SysAuditLMMachineID_NV { get; set; }
        public Nullable<System.DateTime> SysAuditLMDateTime_DT { get; set; }
    }
}
