//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaizenTDSMvcAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MMOBJ
    {
        public int EMPID { get; set; }
        public int OBJECT { get; set; }
        public int TYPE { get; set; }
        public byte[] LNL_BLOB { get; set; }
        public Nullable<System.DateTime> LASTCHANGED { get; set; }
        public Nullable<int> ACCEPTANCETHRESHOLD { get; set; }
        public Nullable<short> BIO_BODYPART { get; set; }
    }
}
