//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaizenTDSMvcAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDFEMP
    {
        public int ID { get; set; }
        public string COSTCENTER { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public Nullable<int> DEPT { get; set; }
        public Nullable<int> LOCATION { get; set; }
        public Nullable<int> BUILDING { get; set; }
        public Nullable<System.DateTime> FLOOR { get; set; }
        public string OPHONE { get; set; }
        public string EXT { get; set; }
        public Nullable<int> EMPLOYEENUM { get; set; }
        public string SUPLASTNAME { get; set; }
        public string SUPFIRSTNAME { get; set; }
        public string WORKSCHED { get; set; }
        public string BARCODENUM { get; set; }
        public Nullable<System.DateTime> FLDDATE827 { get; set; }
        public string FLDTEXT829 { get; set; }
        public Nullable<int> FLDNUM846 { get; set; }
        public string FLDTEXT848 { get; set; }
        public string FLDTEXT850 { get; set; }
        public Nullable<System.DateTime> FLDDATE872 { get; set; }
    }
}
